/* Auto-generated by genmsg_cpp for file /home/nhanndt/mit/nhan_pkgs/g_detector/msg/featureVector.msg */
#ifndef G_DETECTOR_MESSAGE_FEATUREVECTOR_H
#define G_DETECTOR_MESSAGE_FEATUREVECTOR_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace g_detector
{
template <class ContainerAllocator>
struct featureVector_ {
  typedef featureVector_<ContainerAllocator> Type;

  featureVector_()
  : l_h_distance(0.0)
  , l_e_distance(0.0)
  , r_h_distance(0.0)
  , r_e_distance(0.0)
  , l_h_direction(0.0)
  , l_e_direction(0.0)
  , r_h_direction(0.0)
  , r_e_direction(0.0)
  {
  }

  featureVector_(const ContainerAllocator& _alloc)
  : l_h_distance(0.0)
  , l_e_distance(0.0)
  , r_h_distance(0.0)
  , r_e_distance(0.0)
  , l_h_direction(0.0)
  , l_e_direction(0.0)
  , r_h_direction(0.0)
  , r_e_direction(0.0)
  {
  }

  typedef float _l_h_distance_type;
  float l_h_distance;

  typedef float _l_e_distance_type;
  float l_e_distance;

  typedef float _r_h_distance_type;
  float r_h_distance;

  typedef float _r_e_distance_type;
  float r_e_distance;

  typedef float _l_h_direction_type;
  float l_h_direction;

  typedef float _l_e_direction_type;
  float l_e_direction;

  typedef float _r_h_direction_type;
  float r_h_direction;

  typedef float _r_e_direction_type;
  float r_e_direction;


private:
  static const char* __s_getDataType_() { return "g_detector/featureVector"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "467515a83abd8a7e5f0f9239e1ea6a91"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float32 l_h_distance\n\
float32 l_e_distance\n\
float32 r_h_distance\n\
float32 r_e_distance\n\
float32 l_h_direction\n\
float32 l_e_direction\n\
float32 r_h_direction\n\
float32 r_e_direction\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, l_h_distance);
    ros::serialization::serialize(stream, l_e_distance);
    ros::serialization::serialize(stream, r_h_distance);
    ros::serialization::serialize(stream, r_e_distance);
    ros::serialization::serialize(stream, l_h_direction);
    ros::serialization::serialize(stream, l_e_direction);
    ros::serialization::serialize(stream, r_h_direction);
    ros::serialization::serialize(stream, r_e_direction);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, l_h_distance);
    ros::serialization::deserialize(stream, l_e_distance);
    ros::serialization::deserialize(stream, r_h_distance);
    ros::serialization::deserialize(stream, r_e_distance);
    ros::serialization::deserialize(stream, l_h_direction);
    ros::serialization::deserialize(stream, l_e_direction);
    ros::serialization::deserialize(stream, r_h_direction);
    ros::serialization::deserialize(stream, r_e_direction);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(l_h_distance);
    size += ros::serialization::serializationLength(l_e_distance);
    size += ros::serialization::serializationLength(r_h_distance);
    size += ros::serialization::serializationLength(r_e_distance);
    size += ros::serialization::serializationLength(l_h_direction);
    size += ros::serialization::serializationLength(l_e_direction);
    size += ros::serialization::serializationLength(r_h_direction);
    size += ros::serialization::serializationLength(r_e_direction);
    return size;
  }

  typedef boost::shared_ptr< ::g_detector::featureVector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::g_detector::featureVector_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct featureVector
typedef  ::g_detector::featureVector_<std::allocator<void> > featureVector;

typedef boost::shared_ptr< ::g_detector::featureVector> featureVectorPtr;
typedef boost::shared_ptr< ::g_detector::featureVector const> featureVectorConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::g_detector::featureVector_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::g_detector::featureVector_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace g_detector

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::g_detector::featureVector_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::g_detector::featureVector_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::g_detector::featureVector_<ContainerAllocator> > {
  static const char* value() 
  {
    return "467515a83abd8a7e5f0f9239e1ea6a91";
  }

  static const char* value(const  ::g_detector::featureVector_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x467515a83abd8a7eULL;
  static const uint64_t static_value2 = 0x5f0f9239e1ea6a91ULL;
};

template<class ContainerAllocator>
struct DataType< ::g_detector::featureVector_<ContainerAllocator> > {
  static const char* value() 
  {
    return "g_detector/featureVector";
  }

  static const char* value(const  ::g_detector::featureVector_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::g_detector::featureVector_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 l_h_distance\n\
float32 l_e_distance\n\
float32 r_h_distance\n\
float32 r_e_distance\n\
float32 l_h_direction\n\
float32 l_e_direction\n\
float32 r_h_direction\n\
float32 r_e_direction\n\
";
  }

  static const char* value(const  ::g_detector::featureVector_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::g_detector::featureVector_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::g_detector::featureVector_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.l_h_distance);
    stream.next(m.l_e_distance);
    stream.next(m.r_h_distance);
    stream.next(m.r_e_distance);
    stream.next(m.l_h_direction);
    stream.next(m.l_e_direction);
    stream.next(m.r_h_direction);
    stream.next(m.r_e_direction);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct featureVector_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::g_detector::featureVector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::g_detector::featureVector_<ContainerAllocator> & v) 
  {
    s << indent << "l_h_distance: ";
    Printer<float>::stream(s, indent + "  ", v.l_h_distance);
    s << indent << "l_e_distance: ";
    Printer<float>::stream(s, indent + "  ", v.l_e_distance);
    s << indent << "r_h_distance: ";
    Printer<float>::stream(s, indent + "  ", v.r_h_distance);
    s << indent << "r_e_distance: ";
    Printer<float>::stream(s, indent + "  ", v.r_e_distance);
    s << indent << "l_h_direction: ";
    Printer<float>::stream(s, indent + "  ", v.l_h_direction);
    s << indent << "l_e_direction: ";
    Printer<float>::stream(s, indent + "  ", v.l_e_direction);
    s << indent << "r_h_direction: ";
    Printer<float>::stream(s, indent + "  ", v.r_h_direction);
    s << indent << "r_e_direction: ";
    Printer<float>::stream(s, indent + "  ", v.r_e_direction);
  }
};


} // namespace message_operations
} // namespace ros

#endif // G_DETECTOR_MESSAGE_FEATUREVECTOR_H

