"""autogenerated by genmsg_py from featureVector.msg. Do not edit."""
import roslib.message
import struct


class featureVector(roslib.message.Message):
  _md5sum = "467515a83abd8a7e5f0f9239e1ea6a91"
  _type = "g_detector/featureVector"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 l_h_distance
float32 l_e_distance
float32 r_h_distance
float32 r_e_distance
float32 l_h_direction
float32 l_e_direction
float32 r_h_direction
float32 r_e_direction
"""
  __slots__ = ['l_h_distance','l_e_distance','r_h_distance','r_e_distance','l_h_direction','l_e_direction','r_h_direction','r_e_direction']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       l_h_distance,l_e_distance,r_h_distance,r_e_distance,l_h_direction,l_e_direction,r_h_direction,r_e_direction
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(featureVector, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.l_h_distance is None:
        self.l_h_distance = 0.
      if self.l_e_distance is None:
        self.l_e_distance = 0.
      if self.r_h_distance is None:
        self.r_h_distance = 0.
      if self.r_e_distance is None:
        self.r_e_distance = 0.
      if self.l_h_direction is None:
        self.l_h_direction = 0.
      if self.l_e_direction is None:
        self.l_e_direction = 0.
      if self.r_h_direction is None:
        self.r_h_direction = 0.
      if self.r_e_direction is None:
        self.r_e_direction = 0.
    else:
      self.l_h_distance = 0.
      self.l_e_distance = 0.
      self.r_h_distance = 0.
      self.r_e_distance = 0.
      self.l_h_direction = 0.
      self.l_e_direction = 0.
      self.r_h_direction = 0.
      self.r_e_direction = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_8f.pack(_x.l_h_distance, _x.l_e_distance, _x.r_h_distance, _x.r_e_distance, _x.l_h_direction, _x.l_e_direction, _x.r_h_direction, _x.r_e_direction))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.l_h_distance, _x.l_e_distance, _x.r_h_distance, _x.r_e_distance, _x.l_h_direction, _x.l_e_direction, _x.r_h_direction, _x.r_e_direction,) = _struct_8f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_8f.pack(_x.l_h_distance, _x.l_e_distance, _x.r_h_distance, _x.r_e_distance, _x.l_h_direction, _x.l_e_direction, _x.r_h_direction, _x.r_e_direction))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.l_h_distance, _x.l_e_distance, _x.r_h_distance, _x.r_e_distance, _x.l_h_direction, _x.l_e_direction, _x.r_h_direction, _x.r_e_direction,) = _struct_8f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_8f = struct.Struct("<8f")
